language: bash
os:
  - linux
env:
  - ARCH=x86_64
  - ARCH=i686
script:
  - echo "Hello world!"
  - 'if [ "$ARCH" = "x86_64" ]; then
    echo "64 bit";
    elif [ "$ARCH" = "i686" ]; then
	echo "32 bit";
	fi'

