os:
  - linux

env:
#  - ARCH=x86_64
  - ARCH=i686

notifications:
  email: false

script:
  - echo "Hello world!"
  - uname -a
  - 'if [ "$ARCH" = "x86_64" ]; then
    echo "64 bit";
    ./hello.sh;
    fi'
  - 'if [ "$ARCH" = "i686" ]; then
      echo "32 bit";
      docker run -i -v "${PWD}:/MyProgram" i386/ubuntu:16.04 /bin/bash -c "linux32 --32bit i386 apt update; apt install -y wget; /MyProgram/hello.sh";
    fi'

