os: Windows Server 2012 R2
init: 
  - git config --global core.autocrlf input
    
environment:
  PATH: C:\MinGW\msys\1.0\bin;C:\MinGW\bin;C:\Program Files (x86)\Mono-3.2.3\bin;C:\Python27\scripts;%PATH%  
  matrix:
    - build_platform: "x86"
      build_compiler: "mingw"
      build_bindings: 1

# cache:
#   - src/  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
install:
  
build_script:
  - cd GAPPVEYOR_BUILD_FOLDER
  - gcc -v
  - echo "Here I am"
  - uname -a
  - PATH
  
