os: Windows Server 2012 R2
init: 
  - git config --global core.autocrlf input

environment:
  matrix:
    - build_compiler: "mingw"
    - build_compiler: "cygwin"
    
platform:
  - x86
  - x64

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - gcc -v
  - uname -a
  - PATH
  
