os: Windows Server 2012 R2
init: 
  - git config --global core.autocrlf input

environment:
  matrix:
    - build_compiler: "mingw"
      PATH: C:\MinGW\msys\1.0\bin;C:\MinGW\bin;%PATH%  
    - build_compiler: "cygwin"
      PATH: C:\cygwin\bin;%PATH%  
    
platform:
  - x86
  - x64

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - gcc -v
  - uname -a
  - PATH
  
